main: Trajet.o TrajetSimple.o TrajetCompose.o main.o Cell.o
	g++ -o main main.o Trajet.o TrajetSimple.o TrajetCompose.o Cell.o

main.o: main.cpp
	g++ -c main.cpp

Trajet.o: Trajet.cpp
	g++ -c Trajet.cpp

TrajetSimple.o: TrajetSimple.cpp
	g++ -c TrajetSimple.cpp

TrajetCompose.o: TrajetCompose.cpp
	g++ -c TrajetCompose.cpp

Cell.o: Cell.cpp
	g++ -c Cell.cpp
